# Made with ♥︎  by Eloquencer and Divakar

format = """
[╭─](fg:directory)$directory\
$git_branch$git_metrics$git_status\
$docker_context\
$fill\
$status\
$cmd_duration\
$jobs\
$shell\
$os\
[─╮ ](fg:ubuntu)\
$line_break\
[╰╴](fg:directory)\
[$character]($style)\
"""

right_format = """
[╶╯](fg:ubuntu)\
"""

# add_newline = false

# Color Palette
palette = "Power10"

[palettes.Power10]
# colors
directory = 'cyan'
ubuntu = '#E95420'

# only lowercase names
greydimmed = '#424242'
greydarker = '#242424'
ossymbol = '#AAAAAA' # dimmed white
user = 'green'
userroot = 'red'
sshsymbol = 'green'
hostname = 'green'
python = 'yellow'
# git start ---
orangegit = '#E04D27'
conflicted = 'red'
ahead = 'yellow'
behind = 'yellow'
diverged = 'yellow'
uptodate = 'green'
untracked = 'red'
stashed = '#A52A2A' # redbrown
modified = '#C8AC00' # darker yellow
staged = 'green'
renamed = 'yellow'
deleted = 'orange'
# git end ---
jobs = 'blue'
memory = 'purple'
duration = 'yellow'
fill = '#424242' # greydimmed
status = 'red'
localip = 'green'
# shell = '#424242' # greydimmed

[directory]
format = "[  ]($style)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)"
style = 'fg:directory bold'
home_symbol = "~"
read_only = "\uf023 " # \uf023 ' '
read_only_style = 'red'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false
use_os_path_sep = true
disabled = false

[git_branch]
format = "[ \ue0b1 $symbol$branch(:$remote_branch)]($style)" # \u3009 or u276f #\ueab6 \ue0b1
style = 'fg:orangegit' # NOTE: try something like purple
symbol = "\ue0a0" # \ue702 
disabled = false

[git_status]
style = "fg:orangegit"
format = '([\[$all_status$ahead_behind\]]($style))'
stashed = "[$](fg:stashed) "
disabled = false

[fill]
style = 'fg:fill'
symbol = "\u2500" # "\u2500" "─" # no line: ' '

[status]
format = "[$symbol $hex_status( \uf0a2 $signal_number-$signal_name)]($style)" # \uf0a2  , \ueaa2
style = 'fg:status'
symbol = " \u2717" # \u2717 \uf467 \uebde  ✘
disabled = false

[cmd_duration]
format = "[\ueab5\uf017 $duration]($style)" # \ueab5 \uf017   
style = 'fg:duration'
min_time = 500
disabled = false

[jobs]
format = "[\ueab5](fg:jobs bold)[$symbol $number]($style)" # \u3009
style = 'fg:jobs'
symbol = "\ueb7b" # \ueb7b  \uef0c 省 # '廒' # '󰜎' # ''
symbol_threshold = 1
number_threshold = 2
disabled = false

[shell]
format = "[\ueab5](fg:#FFB65E)[$indicator]($style)"
zsh_indicator = 'zsh'
bash_indicator = 'bash'
style = 'fg:#FFB65E bold'
disabled = false

# Customization and activation of some modules:
# Listed in the order of their position in the module rows above
[os]
format = "$symbol"
disabled = false

[os.symbols]
AIX = "AIX "
Alpaquita = "\uf26a " # \uf26a  # \ue3a5\ue390 
AlmaLinux = "\uf31d " # 
Alpine = "\uf300 " # ""
Amazon = "\uf270 " # ""
Android = "\ue70e " # ""
Arch = "\uf303 " # ""
Artix = "\uf31f " # 
CentOS = "\uf304 " # ""
Debian = "\uf306 " # ""
DragonFly = "\ueef8 " #    🐉
Emscripten = "\u26A1 " # ⚡
EndeavourOS = "\uf322 " # "" # 
Fedora = "\uf30a " # ""
FreeBSD = "\uf30c " # ""
Garuda = "\uf337 " # ""
Gentoo = "\uf30d " # ""
HardenedBSD = "\uf132 " # 
Illumos = "\uf326 " # "🐦"
Kali = "\uf327 " # 
Linux = "\uf17c " # ""
Mabox = "\uf1b2 " #  📦
Macos = "\uf302 " # ""
Manjaro = "\uf312 " # ""
Mariner = "\ue7ae " # \ue7ae 
MidnightBSD = "\ue3e0 " # 🌘
Mint = "\uf30e " # ""
NetBSD = "\u2691 " # ⚑
NixOS = "\uf313 " # ""
OpenBSD = "\uf328 " # ""
OpenCloudOS = "\uf0c2 " # 
openEuler = "\u2208 " # \u2208 ∈
openSUSE = "\uf314 " # ""
OracleLinux = "\u213A " # \u213A ℺ # ⊂⊃ \u2282\u2283
Pop = "\uf32a " # ""
Raspbian = "\uf315 " # ""
Redhat = "\uf316 " # "" # 󱄛
RedHatEnterprise = "\uf316 " # "" # 󱄛
RockyLinux = "\uf32b " # 
Redox = "\uf331 " #   󰺕
Solus = "\uf32d " # "" # " "
SUSE = "\uef6d " # ""
Ubuntu = "[\ueab5](fg:#E95420)[\uf31b](fg:#E95420) " # ""
Ultramarine = "󱙳 " # 🔷
Unknown = "\uf108 " # ""
Void = "\uf32e " #  
Windows = "\uf17a " # ""

[username]
format = "[\ueab6 ](fg:user bold)[$user]($style)[ ]()" # \u276F ❯ \ueab6 
style_user = 'fg:user bold'
style_root = 'fg:userroot bold'
show_always = false
disabled = false

[hostname]
format = '[$ssh_symbol ](fg:sshsymbol bold)[$hostname](fg:hostname bold)[ ]()'
ssh_only = true
ssh_symbol = "\ue36e" # \ue36e '' # '⇒' # ' ' # 'ﬁ⇒'
# trim_at = '.companyname.com'
disabled = false

[direnv]
symbol = 'direnv'
style = 'fg:greydimmed'
format = "[\u3009$symbol $loaded/$allowed ]($style)"
allowed_msg = 'a' # 'ok' # '✓'
not_allowed_msg = '!a' # 'nok' # '!'
denied_msg = 'x' # '✘'
loaded_msg = '+' # "\ueabc" # \ueabc  # '->' # 'yo' # '󰗡' # \udb81\udde1 # '󱥸✓' # '󱥸✓' # 
unloaded_msg = '-' # "\ueabc!" # \ueabc ! # '->!' # 'no' # '󰅚' # '󱥸!' \udb86\udd78
disabled = false

