[settings]
# python_compile = true
experimental = true
idiomatic_version_file_enable_tools = ["python"]
cargo.binstall = true
cargo.binstall_quickinstall = true

[tools]
# Languages
rust = "latest"
# clang = "latest"
# conan = "latest"
go = "latest"
node = "latest"
# deno = "latest"
# julia = "latest"
python = "latest"
uv = "latest"
sqlite = "latest"
usage = "latest" # tab completion (for mise, best handled by mise)

# Pip stuff
# USEFUL_PIP_PKGS=(
#     "icecream" "loguru" # for debugging
#     "colorama" "pyfiglet" # presentation
#     "dash" "plotly" "seaborn" "mysql-connector-python" # data representation and calculation
#     "fireducks" "xarray" "openpyxl"
#     "numpy" "scipy" "pillow"
#     "Cython" "numba" "taichi"
#     "parse" "pendulum" "pydantic" "ruff" "mypy" "pyglet"
#     "keras" "scikit-learn" "torch" # AI/ML
# )

# Cargo Stuff
"cargo:sccache" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-information" = "latest"
"cargo:cargo-deny" = "latest"
# # Profiling
# "cargo:cargo-bloat" = "latest"
# "cargo:cargo-flamegraph" = "latest"

# "cargo:irust" = "latest"
# "cargo:cargo-generate" = "latest"
# "cargo:cargo-nextest" = "latest"
# "cargo:cargo-dist" = "latest"
# "cargo:cargo-inspect" = "latest" # educational

# # Useful rust libs
# rustup component add miri # unavailable in stable
# https://www.namtao.com/rust/
# cargo clippy -- -W clippy::unwrap_used clippy::expect_used
# itertools
# serde
# regex & sqlx | sqlite
# Rayon & dashmap & crossbeam
# Color eyre
# Tracing
# Clap
# Tokio & axum & tonic & yew & reqwest & egui

