[settings]
# python_compile = true
experimental = true
idiomatic_version_file_enable_tools = ["python"]
cargo.binstall = true

[tools]
# Languages
rust = "latest"
# clang = "latest"
# conan = "latest"
# go = "latest"
node = "latest"
# deno = "latest"
# julia = "latest"
python = "latest"
uv = "latest"
sqlite = "latest"

# CLI Tools - outdated in nix
usage = "latest" # tab completion (for mise, best handled by mise)


# Cargo Stuff
"cargo-binstall" = "latest"
"cargo:sccache" = "latest"
"cargo:bacon" = "latest"

# Rust crates
"cargo:cargo-expand" = "latest"
"cargo:cargo-info" = "latest"
"cargo:cargo-deny" = "latest"
# # Profiling
# "cargo:cargo-bloat" = "latest"
# "cargo:cargo-flamegraph" = "latest"

# "cargo:irust" = "latest"
# "cargo:cargo-generate" = "latest"
# "cargo:cargo-nextest" = "latest"
# "cargo:cargo-dist" = "latest"
# "cargo:cargo-inspect" = "latest" # educational

