[settings]
# python_compile = true
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
# Languages
rust = "latest"
# clang = "latest"
# conan = "latest"
# go = "latest"
node = "latest"
# deno = "latest"
# julia = "latest"
python = "latest"
uv = "latest"
sqlite = "latest"

# CLI Tools
just = "latest"
mask = "latest" # CLI task runner from markdown file
usage = "latest" # tab completion (mainly for mise)
tree-sitter = "latest"

